feature: Deep object comparison function
GitAlBo93/SolvingTask pull request #2
Opened 2024-12-18 16:11 UTC by GitAlBo93

Функцию писали на созвоне, сегодня повторил снова с проведённой работой над ошибками.

2024-12-20 04:03 UTC, Limhill requested changes

2024-12-20 04:03 UTC, Limhill commented on src/Tasks/Task_133/Task_133.tsx
> +        const field1 = obj1[key];
Почему бы эти переменные не объявить вне цикла for? Тогда их можно будет использовать в if сверху

2024-12-20 09:38 UTC, GitAlBo93 commented on src/Tasks/Task_133/Task_133.tsx
> +        const field1 = obj1[key];
имеешь ввиду, в начало цикла?

2024-12-21 09:32 UTC, Limhill commented on src/Tasks/Task_133/Task_133.tsx
> +        const field1 = obj1[key];
Да, имел в виду начало цикла

2024-12-21 09:33 UTC, Limhill approved these changes

2024-12-21 10:24 UTC, merged